const $=function(){const s=typeof document<"u"&&document.createElement("link").relList;return s&&s.supports&&s.supports("modulepreload")?"modulepreload":"preload"}(),E=function(t){return"/"+t},k={},_=function(s,n,e){let i=Promise.resolve();if(n&&n.length>0){document.getElementsByTagName("link");const r=document.querySelector("meta[property=csp-nonce]"),a=(r==null?void 0:r.nonce)||(r==null?void 0:r.getAttribute("nonce"));i=Promise.all(n.map(o=>{if(o=E(o),o in k)return;k[o]=!0;const l=o.endsWith(".css"),g=l?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${o}"]${g}`))return;const c=document.createElement("link");if(c.rel=l?"stylesheet":$,l||(c.as="script",c.crossOrigin=""),c.href=o,a&&c.setAttribute("nonce",a),document.head.appendChild(c),l)return new Promise((y,S)=>{c.addEventListener("load",y),c.addEventListener("error",()=>S(new Error(`Unable to preload CSS for ${o}`)))})}))}return i.then(()=>s()).catch(r=>{const a=new Event("vite:preloadError",{cancelable:!0});if(a.payload=r,window.dispatchEvent(a),!a.defaultPrevented)throw r})};function v(){return m.sorting?(document.querySelector(".sort-button__icon").classList.add("rotated"),!0):(document.querySelector(".sort-button__icon").classList.remove("rotated"),!1)}document.querySelector(".tasks__sort-button").addEventListener("click",()=>{v()?m.sorting=!1:m.sorting=!0});window.addEventListener("load",v);const L=Object.freeze(Object.defineProperty({__proto__:null,checkSorting:v},Symbol.toStringTag,{value:"Module"})),d={bookmark:"/images/icons/scenario-icons/bookmark.svg",briefcase:"/images/icons/scenario-icons/briefcase.svg",delete:"/images/icons/scenario-icons/delete.svg",home:"/images/icons/scenario-icons/home.svg",info:"/images/icons/scenario-icons/info.svg",plus:"/images/icons/scenario-icons/plus.svg",sun:"/images/icons/scenario-icons/sun.svg",user:"/images/icons/scenario-icons/user.svg"},f={circle:"/images/icons/task-icons/circle.svg",circleActive:"/images/icons/task-icons/circle-active.svg",delete:"/images/icons/task-icons/delete.svg",star:"/images/icons/task-icons/star.svg",starActive:"/images/icons/task-icons/star-active.svg"};function h(t,s,n,e,i=!1){const r=document.createElement("div");r.classList.add("tasks-list__task",`${t}-${s}`),r.innerHTML=`
	<div class="task-left">
		<button class="task-left__button-circle">
			<img class="button-circle__image" src="${f.circle}">
		</button>
		<div class="task-left__body">
			<span class="task-left__text">${n}</span>
		</div>
	</div>
	<div class="task-right">
		<span class="task-right__data">${e}</span>
		<button class="task-right__button-important">
			<img class="button-important__image" src="${i?f.starActive:f.star}">
		</button>
		<button class="task-right__button-delete">
			<img class="button-delete__image" src="${f.delete}">
		</button>
	</div>`,document.querySelector(".tasks__tasks-list").appendChild(r)}function b(){const t=document.querySelector(".tasks__tasks-list"),s=[...t.childNodes];t&&Array.from(t.childNodes).forEach(i=>{i&&i.remove()});const n=[];s.forEach(e=>{const i=e.classList[1].slice(0,-2),r=Number(e.classList[1].at(-1)),a=e.querySelector(".task-left__text").textContent,o=e.querySelector(".task-right__data").textContent,l=e.querySelector(".task-right__button-important > img").attributes.src.nodeValue===f.starActive,g={DOMname:i,id:r,text:a,data:o,isImportant:l};n.push(g)}),v()?n.sort((e,i)=>new Date(e.data)-new Date(i.data)).sort((e,i)=>e.isImportant-i.isImportant).forEach(e=>{h(e.DOMname,e.id,e.text,e.data,e.isImportant),document.querySelector(`.${e.DOMname}-${e.id} > div > div > span`).clientWidth>=document.querySelector(`.${e.DOMname}-${e.id} > div > div`).clientWidth&&document.querySelector(`.${e.DOMname}-${e.id}`).classList.add("animated")}):n.sort((e,i)=>new Date(i.data)-new Date(e.data)).sort((e,i)=>e.isImportant-i.isImportant).forEach(e=>{h(e.DOMname,e.id,e.text,e.data,e.isImportant),document.querySelector(`.${e.DOMname}-${e.id} > div > div > span`).clientWidth>=document.querySelector(`.${e.DOMname}-${e.id} > div > div`).clientWidth&&document.querySelector(`.${e.DOMname}-${e.id}`).classList.add("animated")})}function D(){let t=JSON.parse(localStorage.getItem("todo-user-js"));return t===null?[{icon:d.user,text:"Все задачи",DOMname:"item-all",isCreated:!1,tasks:[]},{icon:d.sun,text:"Свободное время",DOMname:"item-free-time",isCreated:!1,tasks:[]},{icon:d.briefcase,text:"Рабочие дела",DOMname:"item-work",isCreated:!1,tasks:[]},{icon:d.home,text:"Домашние дела",DOMname:"item-home",isCreated:!1,tasks:[]},{icon:d.bookmark,text:"Избранное",DOMname:"item-favorites",isCreated:!1,tasks:[]}]:t[0]}function O(){let t=JSON.parse(localStorage.getItem("todo-user-js"));return t===null?{sorting:!1}:t[1]}function q(){return u.reduce((s,n)=>(n.tasks=n.tasks.filter(e=>e),s.push(n),s),[])}function p(){let t=q();localStorage.setItem("todo-user-js",JSON.stringify([t,m]))}let u=D(),m=O();u=new Proxy(u,{set:(t,s,n)=>(s!=="length"&&(t[s]=n,p()),!0),deleteProperty:(t,s)=>(delete t[s],p(),!0)});m=new Proxy(m,{set:(t,s,n)=>(s!=="length"&&(t[s]=n,v(),b(),p()),!0)});function I(t,s,n=d.info,e=!1){const i=document.createElement("button");e?(i.classList.add("items-list__item-button-created",`${s}`),i.innerHTML=`
		<div class="item-button-created__prepend">
			<img class="item-button-created__image" src="${n}">
			<div class="item-button__body"><span class="item-button-created__text">${t}</span></div>
		</div>
		<img class="item-button-created__image-delete" src="${d.delete}">`,document.querySelector(".scenarios__items-list").appendChild(i)):(i.classList.add("items-list__item-button",`${s}`),i.innerHTML=`
		<img class="item-button__image" src="${n}">
		<div class="item-button__body"><span class="item-button__text">${t}</span></div>`,document.querySelector(".scenarios__items-list").appendChild(i))}function w(){u.forEach(t=>{I(t.text,t.DOMname,t.icon,t.isCreated)});for(let t=1;t<=u.length;t++)document.querySelector(`.scenarios__items-list > button:nth-child(${t}) > div > img`)?document.querySelector(`.scenarios__items-list > button:nth-child(${t}) > div > div > span`).clientWidth>=document.querySelector(`.scenarios__items-list > button:nth-child(${t}) > div > div`).clientWidth&&document.querySelector(`.scenarios__items-list > button:nth-child(${t})`).classList.add("animated"):document.querySelector(`.scenarios__items-list > button:nth-child(${t}) > div > span`).clientWidth>=document.querySelector(`.scenarios__items-list > button:nth-child(${t}) > div`).clientWidth&&document.querySelector(`.scenarios__items-list > button:nth-child(${t})`).classList.add("animated")}function M(){document.querySelector(".item-all").classList.add("item-active"),u.forEach(t=>{t.tasks.forEach(s=>{h(t.DOMname,s.id,s.text,s.data,s.isImportant),setTimeout(()=>{document.querySelector(`.${t.DOMname}-${s.id} > div > div > span`).clientWidth>=document.querySelector(`.${t.DOMname}-${s.id} > div > div`).clientWidth&&document.querySelector(`.${t.DOMname}-${s.id}`).classList.add("animated")},1e3)}),b()})}_(()=>import("./scenariosAdd.js"),[]);_(()=>import("./scenarioItems.js"),[]);_(()=>Promise.resolve().then(()=>L),void 0);_(()=>import("./showCompletedTasks.js"),[]);_(()=>import("./taskItems.js"),[]);_(()=>import("./deleteElements.js"),[]);w();window.addEventListener("load",()=>{M()});window.addEventListener("keydown",t=>{t.keyCode===75&&t.ctrlKey&&t.altKey&&localStorage.removeItem("todo-user-js")});export{p as a,v as b,I as c,h as d,M as r,d as s,f as t,u,b as w};
